version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        VITE_SUPABASE_URL: ${SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
    image: talknative-app:latest
    env_file:
      - ./.env
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    ports:
      - "80:80"
      - "5173:5173"
      - "8000:8000"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

    volumes:
      - ./app:/app:cached
      - ./frontend:/app/frontend:cached
      - /app/frontend/node_modules

